### PR TITLE
 Rename argument variables (dev -> device, g -> graph)

### PR DESCRIPTION
**Pull request by vbkaisetsu**
This branch renames variable names, and bump the version number to 0.3.1.
(PyPI's package version becomes `0.3.1dev***` that is newer than `0.3.0`, and older than `0.3.1`)

### CODE REVIEW

**Comment by odashi** [comment]
Before updating the version, documents should include enough information about the version of the core library linked from current version.

**Review by odashi — COMMENTED** [review]
Add information about core library's version.

**Review by odashi — APPROVED** [review]
LGTM

**Review by refiute — APPROVED** [review]

**Comment by vbkaisetsu** [comment]
Could you wait merge this?
We have to discuss about versioning and releasing.

**Pull request merged**
